version: '3.1'
services:
    postgres:
      image: postgres
      restart: always
      volumes: 
        - ./pgdata:/var/lib/postgressql/data
      ports:
        - '27017:5432'
      environment:
        POSTGRES_PASSWORD: ${DB_PASS}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_DB: ${DB_NAME}